### ISSUE TITLE
Can you explain in detail how to use it?

### ISSUE THREAD

**Issue by qingchunnh** [Razmoth/AssetIndexReader#2]
I found 31049740.blk but I don't know how to use it

**Comment by Razmoth** [comment]
Extract it using `File -> Extract File` in [AssetStudio-CAB](https://github.com/Razmoth/AssetStudio-CAB), then used the resulted `.bin` file in this tool, should work.
[NOTE: make sure key is set to 0 in `Export Options`]

**Comment by qingchunnh** [comment]
thanks for the answer
