### ISSUE TITLE
How to export AnimationClip

### ISSUE THREAD

**Issue by RabberDakk** [Razmoth/AssetIndexReader#3]
Hello, I apologize if this is not the correct place to ask this question.
I want to extract animationclip, but it fails with an error. 

<img src="https://user-images.githubusercontent.com/59415461/153571829-39ec02fc-f417-447e-80f1-a423bb8fed2a.png" width="400px">
<img src="https://user-images.githubusercontent.com/59415461/153569690-e1245096-35ea-4eb3-9741-291f49f00bb2.png" width="400px"><img src="https://user-images.githubusercontent.com/59415461/153575230-66f95a1d-8797-45fe-8e85-b9adb5a3fdaa.png" width="400px"><img src="https://user-images.githubusercontent.com/59415461/153575286-8e8aecf1-7884-46ae-8e3e-8a55d7168d28.png" width="400px">
<img src="https://user-images.githubusercontent.com/59415461/153571317-ca06338a-5658-425a-a73e-2aa17eaa4ed1.png" width="400px">

If I output raw data (`export > raw > selected assets`), I get a file that looks like it has no content, so is it Animator and AnimationClip are only outputting the class name of the Type? I'm sorry if my understanding is wrong.

#### Data Files I tried

- `blocks/00/16721626/CAB-*` 
- `blocks/00/06848285/CAB-*`

#### Export Options
<img src="https://user-images.githubusercontent.com/59415461/153571556-5a505d8b-0ecf-4621-925b-5286ed56baf6.png" width="400px">

I want to output animationclip in a usable format, is there any way to deal with this?

Thank you for the great tool.

**Comment by Razmoth** [comment]
Greetings.

Not really sure if AssetStudio itself supports exporting animationClips as a standalone usable file.

As for the fixes of animationClip parsing works for few of them from various testing.

An example of working ones is in _07138280.blk_, Djinn model, it could export the model with animationClips merged into FBX container.

Hope you find it helpful.

**Comment by RabberDakk** [comment]
Thanks for your advice. 

I'm still having no success exporting models with animation, GenshinStudio will be force closing :_( `Export objects` is successful, but `Export objects + AnimationClip` is forcefully terminated. I have created a video of the forced termination. (using `00/03470272.blk`)

https://user-images.githubusercontent.com/59415461/158066303-5cf23dff-ff6e-45bc-93ce-0d9099099455.mp4

also I have CBT2 / 2.0 / 2.4 / 2.5 blocks, but `07138280.blk` was not included in any of them. `07138280.blk` is included in which version?

**Comment by RabberDakk** [comment]
If I forcefully catch the error and ignore it, an FBX with animationclip will be output. However, the position were broken and the bone ref were lost (only EyeBone and Hair were restored).

```cpp
try {
    var binding = m_ClipBindingConstant.FindBinding(index);
    ...
} catch {
    curveIndex++;
}
```
<img src="https://user-images.githubusercontent.com/59415461/158083963-c9d34a36-22cb-4e30-add0-d8c10ff2a8da.png" width="400px">
<img src="https://user-images.githubusercontent.com/59415461/158083980-5a792514-4d84-40bd-86c9-221820d05a2b.png" width="400px">
<img src="https://user-images.githubusercontent.com/59415461/158084130-4c937155-9acf-44e8-be70-159b513fb3dc.png" width="400px">
