### ISSUE TITLE
[Windows] Can't extract assets_index.json from 31049740.blk

### ISSUE THREAD

**Issue by Preciel** [Razmoth/AssetIndexReader#5]
Trying to extract assets_index.json from 31049740.blk return the following error :

![image](https://user-images.githubusercontent.com/15726325/159164518-ce864343-c06f-4900-aafb-0b9b681a6d1c.png)

**Comment by Razmoth** [comment]
Greetings @Preciel

AssetIndexReader does not support reading from blk file directly, you'll need to extract the the file in it (ends with 06F while Xor is disable) and then pass use that output.

For more info please check the README in ![Genshin Studio](https://github.com/Razmoth/GenshinStudio).

**Comment by Preciel** [comment]
Oh, indeed, didn't understood it like that.

Thanks for the precision !
